<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.1016.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.ProductSnapshot.Core\VirtoCommerce.ProductSnapshot.Core.csproj" />
  </ItemGroup>
</Project>
